/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import dao.Personagem;
import dao.PersonagemDAO;
import dao.Jogador;
import dao.JogadorDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author leoomoreira
 */
public class TelaInserirPersonagem extends javax.swing.JDialog {

    /**
     * Creates new form TelaInserirPessoa
     */
    public TelaInserirPersonagem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotuloNivelPersonagem = new javax.swing.JLabel();
        rotuloNomePersonagem = new javax.swing.JLabel();
        textoNivelPersonagem = new javax.swing.JTextField();
        textoNomePersonagem = new javax.swing.JTextField();
        botaoInserir = new javax.swing.JButton();
        textoIdadePersonagem = new javax.swing.JTextField();
        rotuloIdadePersoangem = new javax.swing.JLabel();
        textoTamanhoPersonagem = new javax.swing.JTextField();
        rotuloTamanhoPersonagem = new javax.swing.JLabel();
        rotuloAlinhamento = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        rotuloJogador = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        rotuloMestre = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        rotuloForca = new javax.swing.JLabel();
        textoForca = new javax.swing.JTextField();
        textoDestreza = new javax.swing.JTextField();
        rotuloDestreza = new javax.swing.JLabel();
        textoConstituicao = new javax.swing.JTextField();
        rotuloConstituicao = new javax.swing.JLabel();
        textoSabedoria = new javax.swing.JTextField();
        rotuloSabedoria = new javax.swing.JLabel();
        textoCarisma = new javax.swing.JTextField();
        rotuloCarisma = new javax.swing.JLabel();
        textoInteligencia = new javax.swing.JTextField();
        rotuloInteligencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Pessoa");
        setName("dialogInserirPessoa"); // NOI18N

        rotuloNivelPersonagem.setText("Nivel:");

        rotuloNomePersonagem.setText("Nome:");

        textoNivelPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNivelPersonagemActionPerformed(evt);
            }
        });

        botaoInserir.setText("Inserir");
        botaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirActionPerformed(evt);
            }
        });

        textoIdadePersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoIdadePersonagemActionPerformed(evt);
            }
        });

        rotuloIdadePersoangem.setText("idade:");

        textoTamanhoPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTamanhoPersonagemActionPerformed(evt);
            }
        });

        rotuloTamanhoPersonagem.setText("tamanho:");

        rotuloAlinhamento.setText("Alinhamento:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordeiro", "Caotico", "Neutro" }));

        rotuloJogador.setText("Jogador:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rotuloMestre.setText("Mestre:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rotuloForca.setText("Forca");

        textoForca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoForcaActionPerformed(evt);
            }
        });

        textoDestreza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDestrezaActionPerformed(evt);
            }
        });

        rotuloDestreza.setText("Destreza");

        textoConstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoConstituicaoActionPerformed(evt);
            }
        });

        rotuloConstituicao.setText("Constituicao");

        textoSabedoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoSabedoriaActionPerformed(evt);
            }
        });

        rotuloSabedoria.setText("Sabedoria");

        textoCarisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCarismaActionPerformed(evt);
            }
        });

        rotuloCarisma.setText("Carisma");

        textoInteligencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoInteligenciaActionPerformed(evt);
            }
        });

        rotuloInteligencia.setText("Inteligencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoInserir)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotuloNomePersonagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoNomePersonagem))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotuloJogador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotuloNivelPersonagem)
                                .addGap(14, 14, 14)
                                .addComponent(textoNivelPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotuloIdadePersoangem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoIdadePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rotuloTamanhoPersonagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoTamanhoPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rotuloMestre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rotuloCarisma)
                                                .addGap(18, 18, 18)
                                                .addComponent(textoCarisma, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rotuloDestreza)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(textoDestreza, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rotuloAlinhamento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rotuloInteligencia)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(textoInteligencia))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rotuloConstituicao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textoConstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rotuloSabedoria)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textoSabedoria, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rotuloForca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoForca, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloNomePersonagem)
                    .addComponent(textoNomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloNivelPersonagem)
                    .addComponent(textoNivelPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotuloIdadePersoangem)
                    .addComponent(textoIdadePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotuloTamanhoPersonagem)
                    .addComponent(textoTamanhoPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloJogador)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotuloMestre)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotuloAlinhamento)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotuloForca)
                            .addComponent(textoForca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotuloConstituicao)
                            .addComponent(textoConstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotuloSabedoria)
                            .addComponent(textoSabedoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotuloInteligencia)
                            .addComponent(textoInteligencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotuloDestreza)
                            .addComponent(textoDestreza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotuloCarisma)
                            .addComponent(textoCarisma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(botaoInserir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente inserir este Personagem?", "Inserir Personagem", JOptionPane.YES_NO_CANCEL_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            try {
                Personagem p = new Personagem();
                p.setNive(Integer.parseInt(textoNivelPersonagem.getText()));
                p.setNome(textoNomePersonagem.getText());
                p.setIdade(Integer.parseInt(textoIdadePersonagem.getText()));
                p.setTamanho(Integer.parseInt(textoTamanhoPersonagem.getText()));
                PersonagemDAO dao = new PersonagemDAO();
                dao.inserir(p);
                textoNivelPersonagem.setText("");
                textoNomePersonagem.setText("");

                JOptionPane.showMessageDialog(this, "Pessoa inserida com sucesso", "Inserir Pessoa", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Inserir Pessoa", JOptionPane.ERROR_MESSAGE);
            }
        }
        botaoInserir.transferFocus();
    }//GEN-LAST:event_botaoInserirActionPerformed
    private void setListJogadores(){
    Jogador a= new Jogador();
    }
    
    
    private void textoNivelPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNivelPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNivelPersonagemActionPerformed

    private void textoIdadePersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoIdadePersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoIdadePersonagemActionPerformed

    private void textoTamanhoPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTamanhoPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTamanhoPersonagemActionPerformed

    private void textoForcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoForcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoForcaActionPerformed

    private void textoDestrezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDestrezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDestrezaActionPerformed

    private void textoConstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoConstituicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoConstituicaoActionPerformed

    private void textoSabedoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoSabedoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoSabedoriaActionPerformed

    private void textoCarismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCarismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCarismaActionPerformed

    private void textoInteligenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoInteligenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoInteligenciaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoInserir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel rotuloAlinhamento;
    private javax.swing.JLabel rotuloCarisma;
    private javax.swing.JLabel rotuloConstituicao;
    private javax.swing.JLabel rotuloDestreza;
    private javax.swing.JLabel rotuloForca;
    private javax.swing.JLabel rotuloIdadePersoangem;
    private javax.swing.JLabel rotuloInteligencia;
    private javax.swing.JLabel rotuloJogador;
    private javax.swing.JLabel rotuloMestre;
    private javax.swing.JLabel rotuloNivelPersonagem;
    private javax.swing.JLabel rotuloNomePersonagem;
    private javax.swing.JLabel rotuloSabedoria;
    private javax.swing.JLabel rotuloTamanhoPersonagem;
    private javax.swing.JTextField textoCarisma;
    private javax.swing.JTextField textoConstituicao;
    private javax.swing.JTextField textoDestreza;
    private javax.swing.JTextField textoForca;
    private javax.swing.JTextField textoIdadePersonagem;
    private javax.swing.JTextField textoInteligencia;
    private javax.swing.JTextField textoNivelPersonagem;
    private javax.swing.JTextField textoNomePersonagem;
    private javax.swing.JTextField textoSabedoria;
    private javax.swing.JTextField textoTamanhoPersonagem;
    // End of variables declaration//GEN-END:variables


}
