/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import dao.Arma;
import dao.ArmaDAO;
import dao.ArmaPersonagem;
import dao.ArmaPersonagemDAO;
import dao.Classe;
import dao.ClasseDAO;
import dao.Idioma;
import dao.IdiomaDAO;
import dao.IdiomaPersonagem;
import dao.IdiomaPersonagemDAO;
import dao.Jogador;
import dao.JogadorDAO;
import dao.Mestre;
import dao.MestreDAO;
import dao.Personagem;
import dao.PersonagemDAO;
import dao.Raca;
import dao.RacaDAO;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author leoomoreira
 */
public class TelaInserirArmaPersonagem extends javax.swing.JDialog {

    /**
     * Creates new form TelaInserirPessoa
     */
    public TelaInserirArmaPersonagem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaPessoas.setModel(new DefaultListModel<String>());
        ChangeOptionsJogador();
        jComboBoxPersonagem.setEnabled(false);
        jComboBoxArma.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoInserir = new javax.swing.JButton();
        rotuloNomeDadoClasse9 = new javax.swing.JLabel();
        rotuloNomeDadoClasse18 = new javax.swing.JLabel();
        jComboBoxJogador = new javax.swing.JComboBox<>();
        jComboBoxPersonagem = new javax.swing.JComboBox<>();
        Consultarjogador = new javax.swing.JButton();
        ConsultarPersonagem = new javax.swing.JButton();
        jLabelNomePersonagem = new javax.swing.JLabel();
        scrollListaPessoas1 = new javax.swing.JScrollPane();
        listaPessoas = new javax.swing.JList<>();
        rotuloNomeDadoClasse19 = new javax.swing.JLabel();
        jComboBoxArma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Personagem");
        setName("dialogInserirPessoa"); // NOI18N

        botaoInserir.setText("Inserir");
        botaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirActionPerformed(evt);
            }
        });

        rotuloNomeDadoClasse9.setText("Jogador");

        rotuloNomeDadoClasse18.setText("Personagem");

        Consultarjogador.setText("Consultar");
        Consultarjogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarjogadorActionPerformed(evt);
            }
        });

        ConsultarPersonagem.setText("Consultar");
        ConsultarPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarPersonagemActionPerformed(evt);
            }
        });

        jLabelNomePersonagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomePersonagem.setText("Nome do personagem");

        listaPessoas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollListaPessoas1.setViewportView(listaPessoas);

        rotuloNomeDadoClasse19.setText("Arma");

        jComboBoxArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxArmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rotuloNomeDadoClasse9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rotuloNomeDadoClasse18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConsultarPersonagem)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Consultarjogador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelNomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotuloNomeDadoClasse19, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxArma, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrollListaPessoas1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloNomeDadoClasse9)
                    .addComponent(jComboBoxJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consultarjogador)
                    .addComponent(jLabelNomePersonagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotuloNomeDadoClasse18)
                            .addComponent(jComboBoxPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultarPersonagem))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotuloNomeDadoClasse19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoInserir))))
                    .addComponent(scrollListaPessoas1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente inserir esta Arma?", "Inserir Arma", JOptionPane.YES_NO_CANCEL_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            try {
                ArmaPersonagem p = new ArmaPersonagem();          
                ArmaPersonagemDAO jDAO = new ArmaPersonagemDAO();
                PersonagemDAO pDAO = new PersonagemDAO();
                ArmaDAO aDAO = new ArmaDAO();
                p.setIdPersonagem(pDAO.obterPorNome(jComboBoxPersonagem.getSelectedItem().toString()).get(0).getId());
                p.setArma(aDAO.obterPorNome(jComboBoxArma.getSelectedItem().toString()).get(0).getId());
                System.out.println(p.getIdPersonagem());
                System.out.println(p.getArma());
                jDAO.inserir(p);
                ActionEvent a=null;
                ConsultarPersonagemActionPerformed(a);
       
                JOptionPane.showMessageDialog(this, "Arma inserido com sucesso", "Inserir Arma", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Inserir Arma", JOptionPane.ERROR_MESSAGE);
            }
        }
        botaoInserir.transferFocus();
    }//GEN-LAST:event_botaoInserirActionPerformed

    private void ConsultarjogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarjogadorActionPerformed
        try {
            JogadorDAO jDAO = new JogadorDAO();
            Jogador j = jDAO.obterPorNome(jComboBoxJogador.getSelectedItem().toString()).get(0);
            PersonagemDAO pDAO = new PersonagemDAO();
            ChangeOptionsPersonagem(pDAO.obterPorJogador(j));
            
        } catch (Exception ex) {
            Logger.getLogger(TelaInserirArmaPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConsultarjogadorActionPerformed

    private void ConsultarPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarPersonagemActionPerformed
        try {
           
            PersonagemDAO p = new PersonagemDAO();
            Personagem per= p.obterPorNome(jComboBoxPersonagem.getSelectedItem().toString()).get(0);
            jLabelNomePersonagem.setText(per.getNome());
            displayArmasPersonagem(per);
            ChangeOptionsArma();
            
            
        } catch (Exception ex) {
            Logger.getLogger(TelaInserirArmaPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConsultarPersonagemActionPerformed

    private void jComboBoxArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxArmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxArmaActionPerformed
    private void displayArmasPersonagem(Personagem p){
        try {
            
            ArmaPersonagemDAO apDAO = new ArmaPersonagemDAO();
            
            List<ArmaPersonagem> arsenal = apDAO.obterTodosDoPersonagem(p.getId());
            DefaultListModel<String> listModel1 = (DefaultListModel<String>) listaPessoas.getModel();
            listModel1.clear();
            ArmaDAO a= new ArmaDAO();
            Arma ar = new Arma();
            for (ArmaPersonagem ap : arsenal) {
                ar = a.obter(ap.getArma());
                listModel1.addElement("nome: "+ar.getNome() + " - tipo de dano: " +ar.getTipoDeDano()+" - dano: "+ar.getDano());
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaInserirArmaPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    
    } 
    private void ChangeOptionsJogador(){
        try {
            jComboBoxJogador.removeAllItems();
            JogadorDAO jDAO = new JogadorDAO();
            List<Jogador> Jogadores = jDAO.obterTodos();
            for(int i = 0;Jogadores.size()>i;i++){
                jComboBoxJogador.addItem(Jogadores.get(i).getNome());
            }

            
        } catch (Exception ex) {
            Logger.getLogger(TelaAtualizarJogador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void ChangeOptionsPersonagem(List<Personagem> personagens){
        try {
            jComboBoxPersonagem.removeAllItems();
            for(int i = 0;personagens.size()>i;i++){
                jComboBoxPersonagem.addItem(personagens.get(i).getNome());
            }
            jComboBoxPersonagem.setEnabled(true);

            
        } catch (Exception ex) {
            Logger.getLogger(TelaAtualizarJogador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private void ChangeOptionsArma(){
        try {
            jComboBoxArma.removeAllItems();
            ArmaDAO jDAO = new ArmaDAO();
            List<Arma> Armas = jDAO.obterTodos();
            for(int i = 0;Armas.size()>i;i++){
                jComboBoxArma.addItem(Armas.get(i).getNome());
            }
            jComboBoxArma.setEnabled(true);

            
        } catch (Exception ex) {
            Logger.getLogger(TelaAtualizarJogador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    
    
   
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarPersonagem;
    private javax.swing.JButton Consultarjogador;
    private javax.swing.JButton botaoInserir;
    public javax.swing.JComboBox<String> jComboBoxArma;
    public javax.swing.JComboBox<String> jComboBoxJogador;
    public javax.swing.JComboBox<String> jComboBoxPersonagem;
    private javax.swing.JLabel jLabelNomePersonagem;
    private javax.swing.JList<String> listaPessoas;
    private javax.swing.JLabel rotuloNomeDadoClasse18;
    private javax.swing.JLabel rotuloNomeDadoClasse19;
    private javax.swing.JLabel rotuloNomeDadoClasse9;
    private javax.swing.JScrollPane scrollListaPessoas1;
    // End of variables declaration//GEN-END:variables
}
