/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import dao.Mestre;
import dao.MestreDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author leoomoreira
 */
public class TelaAtualizarMestre extends javax.swing.JDialog {

    /**
     * Creates new form TelaAtualizarPessoa
     */
    public TelaAtualizarMestre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ChangeOptions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotuloCodigo = new javax.swing.JLabel();
        rotuloNome = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JTextField();
        textoNome = new javax.swing.JTextField();
        botaoAtualizar = new javax.swing.JButton();
        botaoConsultar = new javax.swing.JButton();
        idJogadores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar Pessoa");
        setName("dialogAtualizarPessoa"); // NOI18N

        rotuloCodigo.setText("Código:");

        rotuloNome.setText("Nome:");

        textoNome.setEnabled(false);

        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.setEnabled(false);
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        botaoConsultar.setText("Consultar");
        botaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarActionPerformed(evt);
            }
        });

        idJogadores.setModel(idJogadores.getModel());
        idJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idJogadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotuloCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoAtualizar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotuloNome)
                        .addGap(24, 24, 24)
                        .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloCodigo)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoConsultar)
                    .addComponent(idJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotuloNome)
                    .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoAtualizar)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente atualizar este Mestre?", "Atualizar Mestre", JOptionPane.YES_NO_CANCEL_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            try {
                Mestre p = new Mestre();
                p.setId(Integer.parseInt(textoCodigo.getText()));
                p.setNome(textoNome.getText());
                MestreDAO dao = new MestreDAO();
                dao.atualizar(p);
                textoCodigo.setEnabled(true);
                idJogadores.setEnabled(true);
                botaoConsultar.setEnabled(true);
                textoNome.setEnabled(false);
                botaoAtualizar.setEnabled(false);
                textoCodigo.setText("");
                textoNome.setText("");
                ChangeOptions();
                JOptionPane.showMessageDialog(this, "Mestre atualizado com sucesso", "Atualizar Mestre", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Atualizar Mestre", JOptionPane.ERROR_MESSAGE);
            }
        }
        botaoAtualizar.transferFocus();
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        try {
            MestreDAO dao = new MestreDAO();
            Mestre p = dao.obterPorNome(idJogadores.getSelectedItem().toString()).get(0);
            textoNome.setText(p.getNome());
            textoCodigo.setText(Integer.toString(p.getId()));
            textoCodigo.setEnabled(false);
            idJogadores.setEnabled(false);
            botaoConsultar.setEnabled(false);
            textoNome.setEnabled(true);
            botaoAtualizar.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Consultar Mestre", JOptionPane.ERROR_MESSAGE);
        }
        botaoConsultar.transferFocus();
    }//GEN-LAST:event_botaoConsultarActionPerformed

    private void idJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idJogadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idJogadoresActionPerformed
    private void ChangeOptions(){
        try {
            idJogadores.removeAllItems();
            MestreDAO jDAO = new MestreDAO();
            List<Mestre> Mestres = jDAO.obterTodos();
            for(int i = 0;Mestres.size()>i;i++){
                idJogadores.addItem(Mestres.get(i).getNome());
            }

            
        } catch (Exception ex) {
            Logger.getLogger(TelaAtualizarMestre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoConsultar;
    public javax.swing.JComboBox<String> idJogadores;
    private javax.swing.JLabel rotuloCodigo;
    private javax.swing.JLabel rotuloNome;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoNome;
    // End of variables declaration//GEN-END:variables
}
